name: Android

on:
  workflow_dispatch:

env:
  PROJECT_NAME: ScaleRemapper
  BUILD_TYPE: Release
  RELEASE_DIR: ${{ github.workspace }}/android/app/build/outputs/apk/release
  

jobs:
  build:
    runs-on: ubuntu-latest
    name: ubuntu
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: 'recursive'

      - name: Set Up Cmake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.24.1 

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Debug
        run: ls /usr/local/lib/android/sdk/build-tools/

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set Up Yarn
        run: npm install -g yarn

      - name: Install Linux Deps
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update &&  \
            sudo apt install \
              libasound2-dev \
              libcurl4-openssl-dev \
              libx11-dev \
              libxinerama-dev \
              libxext-dev \
              libfreetype6-dev \
              libwebkit2gtk-4.0-dev \
              libglu1-mesa-dev

      - name: Install UI Dependencies
        working-directory: ./ui
        run: yarn install

      - name: Build UI Bundle
        working-directory: ./ui
        run: yarn build

      - name: Make Gradlew Executable
        working-directory: ./android
        run: chmod +x ./gradlew
        
      - name: Build
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Sign
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ${{ env.RELEASE_DIR }}
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASS }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASS }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ steps.sign.outputs.signedReleaseFile }}