name: CMake iOS

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  PROJECT_NAME: ScaleRemapper

jobs:
  build:
    strategy:
      matrix:
        runner: ['macos']
    runs-on: ${{ matrix.runner }}-latest
    name: ${{ matrix.runner }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_PAT}}
          submodules: 'recursive'

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
          P12_PASSWORD: ${{ secrets.APPLE_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPLE_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$APPLE_CERT_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$APPLE_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$APPLE_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$APPLE_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$APPLE_P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Set Up Yarn
        run: npm install -g yarn

      - name: Install UI Dependencies
        working-directory: ./ui
        run: yarn install

      - name: Build UI Bundle
        working-directory: ./ui
        run: yarn build

      - name: Patch Blocks
        working-directory: ./external/roli_blocks_basics
        run: git apply --reject --whitespace=fix -v ../../scripts/patches/roli.patch

      - name: Patch React-Juce
        working-directory: ./external/react-juce
        run: git apply --reject --whitespace=fix -v ../../scripts/patches/react.patch

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build-ios -G Xcode -D CMAKE_BUILD_TYPE=Release -D CMAKE_SYSTEM_NAME=iOS -D CMAKE_OSX_DEPLOYMENT_TARGET=15.0 -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY="Apple Development" -D CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM=VN2HUYH284

      - name: Build
        run: cmake --build ${{github.workspace}}/build-ios --config=Release -- -allowProvisioningUpdates

      - name: Zip
        working-directory: ${{github.workspace}}/build-ios/${{env.PROJECT_NAME}}_artefacts/${{env.BUILD_TYPE}}
        run: cmake -E tar cv ${{github.workspace}}/build-ios/${{env.PROJECT_NAME}}_${{ matrix.runner }}.zip --format=zip Standalone/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.PROJECT_NAME}}_${{ matrix.runner }}
          path: ${{github.workspace}}/build/${{env.PROJECT_NAME}}_${{ matrix.runner }}.zip
          if-no-files-found: error
          retention-days: 1
